version: "3"
services:
  soulseekarr:
    restart: unless-stopped
    container_name: soulseekarr
    hostname: soulseekarr
    environment:
      - TZ=UTC
      # Script interval in seconds
      - LOOP_INTERVAL=300
    user: "1000:1000"
    volumes:
      # /downloads should typically match slskd.download_dir in your config file or SLSKD_DOWNLOAD_DIR env.
      - /path/to/slskd/downloads:/downloads
      # /data is where the script/container expects the config file to be by default unless --config-dir is set.
      - /path/to/config/dir:/data
    image: docker.io/cryobry/soulseekarr:latest
