version: "3"
services:
  seekarr:
    restart: unless-stopped
    container_name: seekarr
    hostname: seekarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # Script interval in seconds
      - SCRIPT_INTERVAL=300
    user: "1000:1000"
    volumes:
      # /downloads should typically match slskd.download_dir in your config file or SLSKD_DOWNLOAD_DIR env.
      - /path/to/slskd/downloads:/downloads
      # /data is where the script/container expects the config file to be by default unless --config-dir is set.
      - /path/to/config/dir:/data
    image: cryobry/seekarr:latest
